### PR TITLE
[FIX] aeroo_report: add options create=True

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/aeroo_reports/pull/61).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#62

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#62

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#62

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#62

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#62

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#62

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#62

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#62

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#62

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#62

**Pull request closed without merging**
