### PR TITLE
[FW][REM] deprecated report_aeroo_sample module

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/aeroo_reports#73

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/aeroo_reports/pull/75).

**Comment by fw-bot-adhoc** [comment]
This PR targets 17.0 and is part of the forward-port chain. Further PRs will be created up to 18.0.

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@jjscarafia ci/runbot-modified-modules failed on this forward-port PR

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+ override=ci/runbot-modified-modules

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/runbot-modified-modules

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@jjscarafia you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia: you are not allowed to override this status.

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/runbot-modified-modules

**Pull request closed without merging**
