### PR TITLE
13.0 report to printer

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by jjscarafia** [comment]
@roboadhoc r+ override ci/oba_without_tests

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/aeroo_reports/pull/38).

**Comment by roboadhoc** [comment]
I'm sorry, @jjscarafia. You are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
@nicomacr, you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward

**Comment by jjscarafia** [comment]
@roboadhoc override=ci/oba_without_tests

**Pull request closed without merging**
