### PR TITLE
[MIG] base_report_to_printer_aeroo: Migration to 16.0

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/aeroo_reports/pull/56).

**Comment by nicomacr** [comment]
@roboadhoc override=ci/runbot-oba r+

**Comment by roboadhoc** [comment]
@nicomacr you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr: you are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/runbot-oba

**Pull request closed without merging**
