### PR TITLE
[IMP] report_aeroo: new option 'attachment'

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/aeroo_reports/pull/59).

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#60

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#60

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#60

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#60

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#60

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#60

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#60

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#60

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#60

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti @jjscarafia this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#60

**Pull request closed without merging**
