### PR TITLE
[FIX] aeroo_report: get_lang from environment

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/aeroo_reports/pull/63).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#64

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/aeroo_reports#64

**Pull request closed without merging**
