### PR TITLE
[FIX] aeroo_report: product_catalog_generation

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/aeroo_reports/pull/65).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by jcadhoc** [comment]
@roboadhoc r-

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
